
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5435/ewm_stats
spring.datasource.username=ewm_admin
spring.datasource.password=ewm_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true